name: Deploy to GitHub Pages
on:
    push:
        branches:
            - default
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v1
                with:
                    ref: default
            -
                name: Build
                run: |
                    npm install
                    npx sapper export
                    mv __sapper__/export dist
            -
                name: Deploy
                uses: JamesIves/github-pages-deploy-action@releases/v3
                with:
                    GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
                    BRANCH: master
                    FOLDER: dist
