name: Deploy to GitHub Pages
on:
    push:
        branches:
            - default
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            -
                name: Install SSH Client
                uses: webfactory/ssh-agent@v0.2.0
                with:
                    ssh-private-key: '${{ secrets.DEPLOY_KEY }}'
            -
                name: Checkout
                uses: actions/checkout@v1
                with:
                    ref: default
            -
                name: Init checkout
                uses: actions/checkout@v2
                with:
                    ref: default
            -
                name: Checkout code with tags
                run: git fetch --prune --unshallow
            -
                name: Update credits.txt
                run: sh ./credits.sh
                    if ! git diff --exit-code static/credits.txt;
                    then
                        echo "Credits have changed, pushing changes..."
                        git add static/credits.txt
                        git commit -m "auto update static/credits.txt"
                        remote_repo="https://${GITHUB_ACTOR}:${secrets.GITHUB_TOKEN}@github.com/${REPOSITORY}.git"
                        branch=default
                        git push "${remote_repo}" HEAD:${branch}
                    else
                        echo "No changes to credits."
                    fi
            -
                name: Commit files
                run: git commit -m "Add changes" -a
                    git config --local user.email "action@github.com"
                    git config --local user.name "GitHub Action"
                    git commit -m "Add changes" -a
            -
                name: Push changes
                uses: ad-m/github-push-action@master
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
            -
                name: Build
                run: |
                    npm install
                    npx sapper export
                    mv __sapper__/export dist
            -
                name: Deploy
                uses: JamesIves/github-pages-deploy-action@releases/v3
                with:
                    SSH: true
                    BRANCH: master
                    FOLDER: dist
                    CLEAN: true
